<a href="https://colab.research.google.com/github/koushikac/Data_science-Assignments/blob/main/Baston_assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
phi=np.loadtxt('/content/train.csv',delimiter=',',dtype='float',skiprows=1, usecols=tuple(range(1,14)))
display(phi)

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.06380e+02, 1.72800e+01],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, ..., 1.82000e+01,
        3.96330e+02, 6.21000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        3.63430e+02, 4.59000e+00],
       ...,
       [6.65492e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 1.39900e+01],
       [1.31170e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        3.87690e+02, 1.40900e+01],
       [6.46600e-02, 7.00000e+01, 2.24000e+00, ..., 1.48000e+01,
        3.68240e+02, 4.97000e+00]])

In [3]:
y = np.loadtxt('/content/train.csv', dtype='float', delimiter=',', skiprows=1, usecols=14, ndmin=2)
display(y)

array([[14.8],
       [25. ],
       [41.3],
       [18.4],
       [19.8],
       [20.6],
       [15. ],
       [13.4],
       [23.1],
       [19.8],
       [50. ],
       [22. ],
       [21.7],
       [ 5. ],
       [26.7],
       [ 8.3],
       [16.1],
       [20.2],
       [28.5],
       [20.8],
       [29.4],
       [24.3],
       [18.1],
       [22.1],
       [24. ],
       [39.8],
       [18.4],
       [27.1],
       [23.9],
       [24.5],
       [21.2],
       [19.2],
       [20. ],
       [29.6],
       [19.1],
       [10.5],
       [28.1],
       [29. ],
       [20.9],
       [20.6],
       [30.5],
       [22.4],
       [33.8],
       [16.6],
       [28.4],
       [19.6],
       [28.2],
       [13.5],
       [17.8],
       [14.2],
       [ 8.4],
       [13.1],
       [15.3],
       [22.9],
       [20.6],
       [14.4],
       [24.4],
       [22.4],
       [29.1],
       [19.2],
       [21. ],
       [ 7.4],
       [16.3],
       [21.7],
       [16.6],
       [20.3],
       [18

In [4]:
phi_test = np.loadtxt('/content/test.csv', delimiter=',', dtype='float', skiprows=1, usecols=tuple(range(1,14)))
display(phi_test)

array([[1.06120e-01, 3.00000e+01, 4.93000e+00, ..., 1.66000e+01,
        3.94620e+02, 1.24000e+01],
       [3.41090e-01, 0.00000e+00, 7.38000e+00, ..., 1.96000e+01,
        3.96900e+02, 6.12000e+00],
       [1.22472e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        2.46500e+01, 1.56900e+01],
       ...,
       [5.36000e-02, 2.10000e+01, 5.64000e+00, ..., 1.68000e+01,
        3.96900e+02, 5.28000e+00],
       [1.04690e-01, 4.00000e+01, 6.41000e+00, ..., 1.76000e+01,
        3.89250e+02, 6.05000e+00],
       [4.55587e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.54700e+02, 7.12000e+00]])

In [5]:
phi.shape, phi_test.shape

((400, 13), (105, 13))

In [6]:
phi_test = np.concatenate((phi_test, np.ones((105, 1))), axis=1)
phi = np.concatenate((phi, np.ones((400, 1))), axis=1)

In [7]:
display(phi)
display(phi_test)

array([[9.55770e-01, 0.00000e+00, 8.14000e+00, ..., 3.06380e+02,
        1.72800e+01, 1.00000e+00],
       [2.87500e-02, 2.80000e+01, 1.50400e+01, ..., 3.96330e+02,
        6.21000e+00, 1.00000e+00],
       [1.22358e+00, 0.00000e+00, 1.95800e+01, ..., 3.63430e+02,
        4.59000e+00, 1.00000e+00],
       ...,
       [6.65492e+00, 0.00000e+00, 1.81000e+01, ..., 3.96900e+02,
        1.39900e+01, 1.00000e+00],
       [1.31170e-01, 0.00000e+00, 8.56000e+00, ..., 3.87690e+02,
        1.40900e+01, 1.00000e+00],
       [6.46600e-02, 7.00000e+01, 2.24000e+00, ..., 3.68240e+02,
        4.97000e+00, 1.00000e+00]])

array([[1.06120e-01, 3.00000e+01, 4.93000e+00, ..., 3.94620e+02,
        1.24000e+01, 1.00000e+00],
       [3.41090e-01, 0.00000e+00, 7.38000e+00, ..., 3.96900e+02,
        6.12000e+00, 1.00000e+00],
       [1.22472e+01, 0.00000e+00, 1.81000e+01, ..., 2.46500e+01,
        1.56900e+01, 1.00000e+00],
       ...,
       [5.36000e-02, 2.10000e+01, 5.64000e+00, ..., 3.96900e+02,
        5.28000e+00, 1.00000e+00],
       [1.04690e-01, 4.00000e+01, 6.41000e+00, ..., 3.89250e+02,
        6.05000e+00, 1.00000e+00],
       [4.55587e+00, 0.00000e+00, 1.81000e+01, ..., 3.54700e+02,
        7.12000e+00, 1.00000e+00]])

In [8]:
for i in range(0,13):
  col_max = max(phi[:, i])
  col_min = min(phi[:, i])
  phi[:, i] = (phi[:, i]-col_min)/(col_max - col_min)
  phi_test[:, i] = (phi_test[:, i]-col_min)/(col_max - col_min)

In [9]:
y = np.log(y)

In [10]:
def error_f(p, phi, w):
  if p==2:
    errorf = (2 * (np.dot(np.dot(np.transpose(phi), phi), w) - np.dot(np.transpose(phi),y)) + lambd * p * np.power(np.absolute(w),(p-1)))
  if p < 2 and p > 1:
    errorf = (2 * (np.dot(np.dot(np.transpose(phi), phi),w) - np.dot(np.transpose(phi), y))+ lambd * p * np.power(np.absolute(w), (p-1)) * np.sign(w))
  return errorf

In [11]:
# Dictionary containing filenames as keys and p as values
filenames = {'result.csv': 2.0,
             'result_p1.csv': 1.75,
             'result_p2.csv': 1.5,
             'result_p3.csv': 1.3
             }

# For each item in this dictionary
for (fname, p) in filenames.items():
    # Set initial w to zeros
    w = np.zeros((14, 1))

    # Hyperparameter lambda value
    lambd = 0.2

    # Maximum step size
    t = 0.00012

    # Calculate new value of w
    w_new = w - t * error_f(p, phi, w)

    i = 0
    # Repeat steps until error between consecutive w is less than threshold
    while(np.linalg.norm(w_new-w) > 10 ** -10):
        w = w_new
        w_new = w - t * error_f(p, phi, w)
        i = i + 1

    # Load values of id
    id_test = np.loadtxt('/content/test.csv', dtype='int', delimiter=',',
                         skiprows=1, usecols=0, ndmin=2)

    # Calculate y for test data
    y_test = np.exp(np.dot(phi_test, w_new))

    # Save the ids and y
    np.savetxt(fname, np.concatenate((id_test, y_test), axis=1),
               delimiter=',', fmt=['%d', '%f'], header='ID,MEDV')